# Generated by Django 5.1.1 on 2024-09-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items", models.CharField(max_length=1000)),
                ("firstname", models.CharField(max_length=200)),
                ("lastname", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=1000)),
                ("address2", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("province", models.CharField(max_length=200)),
                ("zipcode", models.CharField(max_length=200)),
            ],
        ),
    ]
