# Generated by Django 5.1.1 on 2024-09-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="zipcode",
            new_name="postcode",
        ),
    ]
